version: "3"

services:
  api:
    build: ./
    ports: ['5000:5000']
    volumes: ['./src:/app/src']
    entrypoint:
      - pipenv
      - run
      - flask
      - run
      - --host=0.0.0.0
    environment:
      - FLASK_DEBUG=1
      - FLASK_ENV=development
      - FLASK_APP=/app/src/main.py
      - NAKIRI_KEY=${NAKIRI_KEY}
