version: "3"

services:
  api:
    build: ./
    ports: ['5000:5000']
    volumes: ['./src:/app/src']
    entrypoint:
      - pipenv
      - run
      - flask
      - run
      - --host=0.0.0.0
    environment:
      FLASK_DEBUG: 1
      FLASK_APP: ./src/main.py
