version: "3"

services:
  api:
    build: ./
    container_name: nakiri
    ports: ['5000:5000']
    entrypoint:
      - ./entrypoint.sh
    environment:
      - FLASK_DEBUG=1
      - FLASK_ENV=development
      - FLASK_APP=nakiri
      - NAKIRI_KEY=${NAKIRI_KEY}
      - NAKIRI_DB=${NAKIRI_DB}
    volumes:
      - './nakiri:/app/nakiri'
      - './migrations:/app/migrations'
    restart: always
  db:
    image: 'postgres:11.4'
    container_name: nakiri-db
    ports: ['5432:5432']
    environment:
      - POSTGRES_PASSWORD=${NAKIRI_DB_PASSWORD}
    volumes:
      - nakiri-data:/var/lib/postgresql/data
    restart: always

volumes:
  nakiri-data:
