version: "3"

services:
  api:
    build: ./
    container_name: nakiri
    ports: ['5000:5000']
    volumes: ['./nakiri:/app/nakiri']
    entrypoint:
      - ./entrypoint.sh
    environment:
      - FLASK_DEBUG=1
      - FLASK_ENV=development
      - FLASK_APP=nakiri
      - NAKIRI_KEY=${NAKIRI_KEY}
